[package]
name = "amdfix"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = { version = "2.0.0" }
log = { version = "0.4.22" }
env_logger = { version = "0.11.5" }
clap = { version = "4.5.17" }